ViewModels/CaseStudies/CreateCasestudiesVM.cs
namespace LawProject.ViewModels.CaseStudies
{
    public class CreateCasestudiesVM
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public CreateCasestudiesVM()
        {
            
        }
    }
}

Areas/AdminPanel/Controllers/CaseStudiesController.cs
using LawProject.Data;
using LawProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Formatters;
using Microsoft.AspNetCore.Routing.Matching;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;
using System.IO;

namespace LawProject.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    public class CaseStudiesController : Controller
    {
        public readonly LawProjectDbContext _context;
        public readonly IWebHostEnvironment _env;

        public CaseStudiesController(LawProjectDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            List<CaseStudies> caseStudies = _context.CaseStudies.ToList();
            return View(caseStudies);
        }


        public IActionResult Create()
        {

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(CaseStudies caseStudies)
        {
            if (!ModelState.IsValid) return View();
            if (caseStudies == null)
            {
                ModelState.AddModelError("Photo", "Sekil secilmeyib");
                return View();
            }

            if (!caseStudies.Photo.ContentType.Contains("image/"))
            {
                ModelState.AddModelError("Photo", "Sekiil tipi duzgun deyil");
                return View();
            }

            if (caseStudies.Photo.Length / 1024 > 200)
            {
                ModelState.AddModelError("Photo", "Sekil olcusu odemir");
                return View();
            }

            var fileName = Guid.NewGuid().ToString() + "" + caseStudies.Photo.FileName;

            string path = Path.Combine(_env.WebRootPath, "assets/img", fileName);

            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                await caseStudies.Photo.CopyToAsync(stream);
            }
            await _context.CaseStudies.AddAsync(caseStudies);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
 
        }

        public async Task<IActionResult> Delete(int Id)
        {
            if (Id == null || Id < 1) return BadRequest();

            CaseStudies caseStudies = await  _context.CaseStudies.FirstOrDefaultAsync(s => s.Id == Id);

            if (caseStudies == null) return NotFound();

            string path = Path.Combine(_env.WebRootPath, "img", caseStudies.Image);

            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            _context.CaseStudies.Remove(caseStudies);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int Id)
        {
            if(Id==null || Id < 1)
            {
                return BadRequest();
            }

            CaseStudies caseStudies = await _context.CaseStudies.FirstOrDefaultAsync(s => s.Id == Id);
            if (caseStudies == null)
            {
                return NotFound();
            }

            return View(caseStudies);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CaseStudies caseStudies)
        {
            if (!ModelState.IsValid) return View();

            CaseStudies old = await _context.CaseStudies.FirstOrDefaultAsync(s => s.Id == caseStudies.Id);

            if(old == null) return NotFound();

            if (caseStudies.Photo != null)
            {
                if (!caseStudies.Photo.ContentType.Contains("image/"))
                {
                    ModelState.AddModelError("Photo", "Sekil tipi duzgun deyil");
                    return View();
                }
                if (caseStudies.Photo.Length / 1024 > 200)
                {
                    ModelState.AddModelError("Photo", "Olcu uygun deyil");
                    return View();
                }
            }

            string oldpath = Path.Combine(_env.WebRootPath, "assets/img", old.Image);
            if (System.IO.File.Exists(oldpath))
            {
                System.IO.File.Delete(oldpath);
            }
            var fileName = Guid.NewGuid().ToString() + " " + caseStudies.Photo.FileName;
            old.Image = fileName;

            string newpath = Path.Combine(_env.WebRootPath, "img", fileName);

            using(FileStream stream=new FileStream(newpath, FileMode.Create))
            {
                await caseStudies.Photo.CopyToAsync(stream);
            }

            old.Title = caseStudies.Title;
            old.SubTitle = caseStudies.SubTitle;

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Controllers/CaseStudiesController.cs
using LawProject.Data;
using LawProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace LawProject.Controllers
{
    public class CaseStudiesController : Controller
    {
        private readonly LawProjectDbContext _context;
        public CaseStudiesController(LawProjectDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<CaseStudies> caseStudies = _context.CaseStudies.ToList();
            return View(caseStudies);
        }
    }
}

Areas/AdminPanel/Views/CaseStudies/Create.cshtml
@using LawProject.Models;
@model CaseStudies

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Case Studies</h4>
                        <form class="forms-sample" method="post" enctype="multipart/form-data">
                            
                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input asp-for="Photo" type="text" class="form-control"  placeholder="Photo" />
                                
                                <span asp-validation-for="Photo"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Title">Title</label>
                                <input asp-for="Title" type="text" class="form-control"  placeholder="Title" />
                            </div>

                            <div class="form-group">
                                <label asp-for="SubTitle">Subtitle</label>
                                <input asp-for="SubTitle" type="text" class="form-control"  placeholder="Subtitle" />
                            </div>

                            <div class="form-group">
                                <label asp-for="Date">Date</label>
                                <input asp-for="Date" type="text" class="form-control" placeholder="Date" />
                            </div>


                            

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Areas/AdminPanel/Views/CaseStudies/Index.cshtml
@using LawProject.Models;
@model List<CaseStudies>

@{
    int count = 1;
}

<div class="col-lg-12 grid-margin stretch-card">

    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Case Studies</h4>

            <a asp-controller="CaseStudies" asp-action="Create" type="button" class="btn btn-info">Add Position</a>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Sira Nomresi
                            </th>
                            <th>
                                Image
                            </th>
                            <th>
                                Title
                            </th>
                            <th>
                                Subtitle
                            </th>
                            <th>
                                Date
                            </th>
                            <th>
                                Setting
                            </th>
                        </tr>
                    </thead>

                    <tbody>

                       @foreach (CaseStudies item in Model)
                       {
                            <tr>
                                <td>
                                    @(count++)
                                </td>
                                <td class="py-1">
                                    <img src="~/assets/img/@item.Image" alt="image"/>
                                </td>
                                <td>
                                    @item.Title
                                </td>
                                
                                <td>
                                    @item.SubTitle
                                </td>
                                <td>
                                    @item.Date
                                </td>
                                <td>
                                    <a asp-controller="CaseStudies" asp-action="update" asp-route-id="@item.Id" class="btn btn-warning"><i class="mdi mdi-grease-pencil"></i></a>
                                    <a asp-controller="CaseStudies" asp-action="delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                            </tr>
                       }
                       
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Areas/AdminPanel/Views/CaseStudies/Update.cshtml
@using LawProject.Models;
@model CaseStudies

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Case Studies</h4>
                        <form class="forms-sample" method="post" enctype="multipart/form-data">
                            <div>
                                <img src="~/assets/img/@Model.Image" />
                            </div>
                            <div class="form-group">
                                <label asp-for="Photo">Photo</label>
                                <input asp-for="Photo" type="text" class="form-control" placeholder="Name" />

                                <span asp-validation-for="Photo"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Title">Title</label>
                                <input asp-for="Title" type="text" class="form-control" value="@Model.Title"  placeholder="Name" />
                            </div>

                            <div class="form-group">
                                <label asp-for="SubTitle">Subtitle</label>
                                <input asp-for="SubTitle" type="text" class="form-control" value="@Model.SubTitle"  placeholder="Name" />
                            </div>
                            <div class="form-group">
                                <label asp-for="Date">Subtitle</label>
                                <input asp-for="Date" type="text" class="form-control" value="@Model.Date" placeholder="Name" />
                            </div>
                            

                            

                            <button type="submit" class="btn btn-primary me-2">Submit</button>
                            <button class="btn btn-light">Cancel</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>